{% set name = "mkdocs-gen-files" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 377bff8ee8e93515916689f483d971643f83a94eed7e92318854da8f344f0163

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - poetry
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs <2.0.0,>=1.0.3

test:
  imports:
    - mkdocs_gen_files
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://oprypin.github.io/mkdocs-gen-files/
  summary: MkDocs plugin to programmatically generate documentation pages during the build
  description: MkDocs plugin to programmatically generate documentation pages during the build
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://oprypin.github.io/mkdocs-gen-files/
  dev_url: https://github.com/oprypin/mkdocs-gen-files

extra:
  recipe-maintainers:
    - cpcloud
