{% set name = "mkdocs-gen-files" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4c7cf256b5d67062a788f6b1d035e157fc1a9498c2399be9af5257d4ff4d19bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gen-files = mkdocs_gen_files.plugin:GenFilesPlugin

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs >=1.4.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - mkdocs_gen_files
  commands:
    - pip check

about:
  home: https://oprypin.github.io/mkdocs-gen-files/
  summary: MkDocs plugin to programmatically generate documentation pages during the build
  description: MkDocs plugin to programmatically generate documentation pages during the build
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://oprypin.github.io/mkdocs-gen-files/
  dev_url: https://github.com/oprypin/mkdocs-gen-files

extra:
  recipe-maintainers:
    - cpcloud
    - dhirschfeld
